name: RunicProfessions
version: ${project.version}
main: com.runicrealms.plugin.RunicProfessions
api-version: 1.13
depend: [ MythicMobs, RunicCore, RunicItems, RunicCommon, RunicDatabase, RunicRestart ]