name: RunicProfessions
version: ${project.version}
main: com.runicrealms.plugin.RunicProfessions
api-version: 1.13
depend: [MythicMobs,RunicItems]
commands:
  gathertool:
    usage: /<commands>
    description: Give a gathering tool
  setprof:
    usage: /<commands>
    description: Give a gathering tool
  jewelmaster:
    usage: /<commands>
    description: Open jewel master shop
  huntershop:
    usage: /<commands>
    description: Open hunter shop
  proflevel:
    usage: /<commands>
    description: Open hunter shop