name: RunicProfessions
version: ${project.version}
main: com.runicrealms.plugin.professions.RunicProfessions
api-version: 1.13
depend:
  - MythicMobs
  - HolographicDisplays
  - RunicCore
  - RunicChat
  - RunicItems
  - RunicNpcs
  - RunicCommon
  - RunicDatabase
  - RunicRestart