name: RunicProfessions
version: ${project.version}
main: com.runicrealms.plugin.RunicProfessions
api-version: 1.13
commands:
  gathertool:
    usage: /<commands>
    description: Give a gathering tool
  setprof:
    usage: /<commands>
    description: Give a gathering tool
  jewelmaster:
    usage: /<commands>
    description: Open jewel master shop
